DROP TABLE if exists SEAT;
DROP TABLE if exists SEATHOLD;

CREATE TABLE if not exists SEAT(
	SEAT_ID         int auto_increment primary key, 
	ROW_NUMBER       int  not null, 
	SEAT_NUMBER      int  not null,
	DESCRIPTION      varchar(200) not null,  
	SEAT_HOLD_ID     int not null default 0, 
	STATUS          int not null default 0, 
	LAST_HELD_TIME    timestamp default CURRENT_TIMESTAMP
);

CREATE TABLE if not exists SEATHOLD(
	SEAT_HOLD_ID    int auto_increment primary key, 
	EMAIL           varchar(100) not null
);


INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(1,'Stadium View',CURRENT_TIMESTAMP(),1,1,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(2,'Stadium View',CURRENT_TIMESTAMP(),1,2,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(3,'Stadium View',CURRENT_TIMESTAMP(),1,3,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(4,'Stadium View',CURRENT_TIMESTAMP(),1,4,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(5,'Stadium View',CURRENT_TIMESTAMP(),1,5,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(6,'Stadium View',CURRENT_TIMESTAMP(),1,6,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(7,'Stadium View',CURRENT_TIMESTAMP(),1,7,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(8,'Stadium View',CURRENT_TIMESTAMP(),1,8,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(9,'Stadium View',CURRENT_TIMESTAMP(),1,9,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(10,'Stadium View',CURRENT_TIMESTAMP(),1,10,0,0);

INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(11,'Stadium View',CURRENT_TIMESTAMP(),2,1,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(12,'Stadium View',CURRENT_TIMESTAMP(),2,2,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(13,'Stadium View',CURRENT_TIMESTAMP(),2,3,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(14,'Stadium View',CURRENT_TIMESTAMP(),2,4,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(15,'Stadium View',CURRENT_TIMESTAMP(),2,5,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(16,'Stadium View',CURRENT_TIMESTAMP(),2,6,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(17,'Stadium View',CURRENT_TIMESTAMP(),2,7,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(18,'Stadium View',CURRENT_TIMESTAMP(),2,8,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(19,'Stadium View',CURRENT_TIMESTAMP(),2,9,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(20,'Stadium View',CURRENT_TIMESTAMP(),2,10,0,0);

INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(21,'Stadium View',CURRENT_TIMESTAMP(),3,1,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(22,'Stadium View',CURRENT_TIMESTAMP(),3,2,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(23,'Stadium View',CURRENT_TIMESTAMP(),3,3,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(24,'Stadium View',CURRENT_TIMESTAMP(),3,4,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(25,'Stadium View',CURRENT_TIMESTAMP(),3,5,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(26,'Stadium View',CURRENT_TIMESTAMP(),3,6,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(27,'Stadium View',CURRENT_TIMESTAMP(),3,7,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(28,'Stadium View',CURRENT_TIMESTAMP(),3,8,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(29,'Stadium View',CURRENT_TIMESTAMP(),3,9,0,0);
INSERT INTO SEAT(SEAT_ID,DESCRIPTION,LAST_HELD_TIME,ROW_NUMBER,SEAT_NUMBER,SEAT_HOLD_ID,STATUS) VALUES(30,'Stadium View',CURRENT_TIMESTAMP(),3,10,0,0);


